version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      aspire:
        patterns:
          - "Aspire.*"
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
      microsoft-fluentui:
        patterns:
          - "Microsoft.FluentUI.*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
